version: '3.8'

services:
  nord-crm-api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - nord-crm-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    #volumes:
      #- postgres_data:/var/lib/postgresql/data
    networks:
      - nord-crm-network

networks:
  nord-crm-network:
    driver: bridge