spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/}${DB_NAME:nord_crm_db}?useTimezone=true&serverTimezone=UTC?createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
api:
  security:
    jwt:
      secret: ${TOKEN_SECRET:"mySecretKey"}
